# This workflow will build a bash project

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Conventional Commit Checker
      uses: wagoid/commitlint-github-action@v4
    - name: Test
      run: ./test/bats/bin/bats test/